language: ruby
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - jruby-9.1.17.0
  - jruby-9.2.0.0
before_install:
  - gem install bundler
